#!/bin/bash
# Returns a list of files via "stratified random selection" (stratified by
# directory)! Use this to generate playlists where shows with 1,000 episodes
# don't end up dominating most of the list.
#
# See the example in `print_usage()` for an overview.
#
# For handy ways to use this (assuming it's `stratrand` on your `PATH`), edit
# your `~/.bashrc`:
# ```
# alias randshows="stratrand v 25 \${SHOWS} | mpv --playlist=- &>/dev/null &"
#
# function randsongs()
# {
#   if (( ${#} != 1 ))
#   then
#     echo "From which directory?"
#     return 1
#   fi
#   stratrand a 25 "${1}" | mpv --playlist=- &>/dev/null &
# }
# ```
# Then you can use it like this:
# ```
# $ randshows
# $ randsongs "~/Music/Rush"
# ```
# The playlist generated by `randshows`, for example, will be a fairer version
# of that generated by
# `mpv --directory-filter-types=video --autocreate-playlist=filter --shuffle`
# because each show subdirectory in your `${SHOWS}` directory will be fairly
# represented across all 25 episodes selected.

function print_usage()
{
    echo -e "\
USAGE
\t${0} <a|v> <n> <dir>

DESCRIPTION
\tReturns a number of files of some format from the given directory via
\tdirectory-stratified random selection

\t\"Directory-stratified random selection\" means that, unlike randomly picking
\t'n' files from 'find dir -type f', files are sampled \"fairly\" from every
\tsubdirectory of 'dir' (arbitrarily-many levels deep) as well as from the files
\tdirectly inside of 'dir'.

\tFor example, take this directory hierarchy:
\t
\tdir/
\t├── toplevelfile0.mp3
\t├── toplevelfile1.mp3
\t├── red
\t│   └── red0.mp3
\t└── blue
\t    ├── blue0.mp3
\t    ├── blue1.mp3
\t    ├── blue2.mp3
\t    ├── blue3.mp3
\t    ├── blue4.mp3
\t    ├── blue5.mp3
\t    ├── blue6.mp3
\t    ├── blue7.mp3
\t    ├── blue8.mp3
\t    └── subdir
\t        └── subdir0.mp3
\t
\tRequesting 4 files from 'dir' will return those files from each of the 3
\t\"strata\" in the hierarchy:
\t
\t\tStratum 1: The files directly inside 'dir' ('toplevelfile*.mp3')
\t\tStratum 2: The single file in 'red/'
\t\tStratum 3: The files in 'blue/' and 'blue/subdir/'
\t
\tThe subdirectories of 'dir/', and the files directly in 'dir/', are treated as
\t\"strata\" from which to randomly pick files. This way, the files in 'blue/'
\tdo not dominate the selection despite being the most numerous. Of the 4 files
\treturned, 2 files will necessarily be from the same stratum. However, that
\tstratum won't be 'red/' since it only has one file (repeated files are not
\tallowed in the output).

\tThis is handy to get a \"fairly\" random playlist of episodes without having
\tshows with more episodes dominate shows with fewer episodes in the playlist.

PARAMETERS
\tREQUIRED
\t\ta|v\tWhat kind of files to get ('a' for audio or 'v' for video)

\t\tn\tThe number of files to get

\t\tdir\tThe directory to return files from" >&2
}

function parse_arguments()
{
    local -r REQUIRED_ARGS=3

    if (( ${#} != REQUIRED_ARGS ))
    then
        return 1
    fi

    local -r FORMAT_ARG="${1}"
    if ! [[ "${FORMAT_ARG}" =~ ^(a|v)$ ]]
    then
        return 1
    else
        if [[ "${FORMAT_ARG}" == "a" ]]
        then
            readonly FORMAT_AUDIO=1
        else
            readonly FORMAT_VIDEO=1
        fi
    fi

    FILES_TO_GET=${2}
    if ! [[ "${FILES_TO_GET}" =~ ^[[:digit:]]+$ ]]
    then
        return 1
    fi

    TOPLEVEL_DIR="${3}"
    if ! [[ -d "${TOPLEVEL_DIR}" ]]
    then
        return 1
    fi

    return 0
}

# Returns whether the file given in `$1` looks like an audio file
function is_audio()
{
    case "${1,,}" in
        *.8svx | \
        *.aa | \
        *.aac | \
        *.aax | \
        *.act | \
        *.aiff | \
        *.alac | \
        *.amr | \
        *.ape | \
        *.au | \
        *.awb | \
        *.cda | \
        *.dct | \
        *.dss | \
        *.dvf | \
        *.flac | \
        *.gsm | \
        *.iklax | \
        *.ivs | \
        *.m4a | \
        *.m4b | \
        *.m4p | \
        *.mmf | \
        *.mp3 | \
        *.mpc | \
        *.msv | \
        *.nmf | \
        *.nsf | \
        *.ogg | \
        *.oga | \
        *.mogg | \
        *.opus | \
        *.ra | \
        *.raw | \
        *.rf64 | \
        *.sln | \
        *.tta | \
        *.voc | \
        *.vox | \
        *.wav | \
        *.wma | \
        *.wv)
            return 0 ;;
        *) return 1 ;;
    esac
}

# Returns whether the file given in `$1` looks like a video file
function is_video()
{
    case "${1,,}" in
        *.3g2 | \
        *.3gp | \
        *.amv | \
        *.asf | \
        *.avi | \
        *.drc | \
        *.flv | \
        *.f4v | \
        *.f4p | \
        *.gif | \
        *.gifv | \
        *.mkv | \
        *.mng | \
        *.mov | \
        *.qt | \
        *.m4v | \
        *.mp4 | \
        *.m4p | \
        *.mpg | \
        *.mp2 | \
        *.mpeg | \
        *.mpe | \
        *.mpv | \
        *.m2v | \
        *.mts | \
        *.m2ts | \
        *.ts | \
        *.mxf | \
        *.nsv | \
        *.ogv | \
        *.rm | \
        *.rmvb | \
        *.roq | \
        *.svi | \
        *.vob | \
        *.webm | \
        *.wmv | \
        *.yuv)
            return 0 ;;
        *) return 1 ;;
    esac
}

# Returns whether the file given in `$1` looks like it's of the format we want
function right_format()
{
    if [[ -v FORMAT_AUDIO ]]
    then
        is_audio "${1}"
    elif [[ -v FORMAT_VIDEO ]]
    then
        is_video "${1}"
    else
        return 1
    fi
}

# Builds a stratum as a global array from an array accessed via nameref in `$1`
# and populates `STRATA_NAMES` with the new stratum's name, generated using the
# stratum index in `$2`
function build_stratum()
{
    local FILE_ARR_NAME="$1"
    local INDEX="$2"
    local -n FILE_ARR="$FILE_ARR_NAME"

    declare -g -a "STRATUM_$INDEX" # Create the stratum as a global array.
    declare -n REF="STRATUM_$INDEX"
    REF=("${FILE_ARR[@]}") # Fill the stratum from the given array of files.
    unset -n REF
    unset -n FILE_ARR

    STRATA_NAMES+=("STRATUM_$INDEX")
}

# Constructs the strata whose files to sample from the files and directories
# directly inside `TOPLEVEL_DIR`
#
# See the example in `print_usage()`.
#
# Since we can't have an array of arrays in Bash, this creates a separate global
# array per stratum with generated names like "STRATUM_0", "STRATUM_1", etc. One
# more global array, `STRATA_NAMES`, is created. To iterate over the strata,
# iterate over `STRATA_NAMES` and, for each name, use a nameref (`declare -n`)
# to reference the stratum with that name:
# ```
# local STRATUM_NAME
# local -n REF
# local i=0
# for STRATUM_NAME in "${STRATA_NAMES[@]}"
# do
#     declare -n REF="$STRATUM_NAME" # Re-establish the nameref
#     printf 'Stratum %d (%s): %d file(s)\n' "$i" "$STRATUM_NAME" "${#REF[@]}"
#     printf '   %s\n' "${REF[@]}"
#     unset -n REF # Unbind the nameref for safety
#     (( i++ ))
# done
# ```
function build_strata()
{
    local -a TMP_ARR=() # Scratch array for building each stratum
    local INDEX=0 # Index baked into the generated name for each stratum

    # Optionally, clean up arrays left over from a hypothetical, previous call:
    local NAME
    for NAME in "${STRATA_NAMES[@]}"; do
        unset "$NAME"
    done
    STRATA_NAMES=() # The global array holding the names of all strata

    # First, create the stratum of the top-level files of `TOPLEVEL_DIR`.
    #
    # `mapfile` runs `find` and loads its NUL-separated list into `TMP_ARR`.
    mapfile -d '' -t TMP_ARR < <(find "${TOPLEVEL_DIR}" -maxdepth 1 -type f -print0)
    if (( ${#TMP_ARR[@]} ))
    then
        build_stratum TMP_ARR "$INDEX"
        (( INDEX++ ))
    fi

    # Then create one stratum per immediate subdirectory of `TOPLEVEL_DIR`.
    local -a SUBDIRS=()
    mapfile -d '' -t SUBDIRS < <(find "${TOPLEVEL_DIR}" -mindepth 1 -maxdepth 1 -type d -print0)

    local SUBDIR
    for SUBDIR in "${SUBDIRS[@]}"
    do
        mapfile -d '' -t TMP_ARR < <(find "${SUBDIR}" -type f -print0)
        if (( ${#TMP_ARR[@]} ))
        then
            build_stratum TMP_ARR "$INDEX"
            (( INDEX++ ))
        fi
    done
}

# Returns whether the file given in `$1` is inside the array given in `$2`
function contains()
{
    local NEEDLE="$1"
    local -n HAYSTACK="$2"

    local FILE
    for FILE in "${HAYSTACK[@]}"
    do
        [[ "$FILE" == "$NEEDLE" ]] && return 0
    done
    return 1
}

# Prints the requested number of files (of the requested format) to stdout,
# returning non-zero when there was a problem doing so
function stratrand()
{
    local -a FILES=()
    local FILES_FOUND=0

    # Identify the strata in the `TOPLEVEL_DIR`.
    build_strata
    if (( ${#STRATA_NAMES[@]} == 0 ))
    then
        return 1
    fi

    # Pick random files from each stratum until we hit the requested number.
    local ATTEMPTS=0 # Passes over all strata that found no files
    local MAX_ATTEMPTS=100
    while (( FILES_FOUND < FILES_TO_GET )) && (( ATTEMPTS < MAX_ATTEMPTS ))
    do
        # In each pass over the strata, randomize the order of the strata. We
        # still go through every stratum on each pass, but randomizing the order
        # of strata means that, when the number of files to get is greater than
        # the number of strata, the strata which contribute repeated files at
        # the end of the search are randomized rather than always being the
        # first strata in `STRATA_NAMES`.
        local -a STRATA_PASS_ORDER
        mapfile -t STRATA_PASS_ORDER < <(printf '%s\n' "${STRATA_NAMES[@]}" | shuf)
        local STRATUM_NAME
        local MADE_PROGRESS=0
        for STRATUM_NAME in "${STRATA_PASS_ORDER[@]}"
        do
            (( FILES_FOUND == FILES_TO_GET )) && break # Prevent overshoot

            local -n REF="$STRATUM_NAME"
            local FILE_INDEX
            FILE_INDEX=$(shuf -i "0-$(( ${#REF[@]} - 1 ))" -n1)
            local RANDOM_FILE="${REF[FILE_INDEX]}"
            if right_format "$RANDOM_FILE" && ! contains "$RANDOM_FILE" FILES
            then
                FILES+=("$RANDOM_FILE")
                (( FILES_FOUND++ ))
                MADE_PROGRESS=1
            fi
            unset -n REF
        done

        if (( MADE_PROGRESS ))
        then
            ATTEMPTS=0
        else
            (( ATTEMPTS++ ))
        fi
    done

    # Report what files we've found.
    local FILE
    for FILE in "${FILES[@]}"
    do
        printf '%s\n' "$FILE"
    done

    # Report whether we found the number of files requested.
    if (( FILES_FOUND != FILES_TO_GET ))
    then
        return 1
    fi
    return 0
}

if ! parse_arguments "${@}"
then
    print_usage

    exit 1
fi

stratrand
